name: Build and Test TodoGenie
on: push

jobs:
    # todogenie-build-linux:
    #     name: Build TodoGenie on Linux
    #     runs-on: ubuntu-latest
    #     steps:
    #         - uses: actions/checkout@v4
    #         - name: Build
    #           shell: pwsh
    #           run: |
    #             ./build.ps1 -Debug
    todogenie-build-windows:
        name: Build TodoGenie on Windows
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4
            - name: Build
              env:
                APIKEY: ${{ secrets.APIKEY }}
              shell: pwsh
              #TODO(#112): Get more then just the list subcommand working with actions
              run: |
                .\build.ps1 -SubCommands List -Debug -RunTests -NoNewSession -ApiKey $env:APIKEY